<a href="https://colab.research.google.com/github/mikemwai/artificial_intelligence/blob/main/artificial_intelligence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
from numpy import array
from scipy.special import softmax

In [23]:
input_vec = array([[1,0,0,1,0],
                   [0,1,0,0,1]])

weight_matrix_1 = array([[.2,.3,.1],
                       [.1,.3,.2],
                       [.4,.6,.8],
                       [.3,.5,.4],
                       [.7,.5,.1]])

weight_matrix_2 = array([[.5,.6],
                         [.9,.7],
                         [.2,.6],
                         [.8,.3],
                         [.1,.9]])

In [24]:
out_1 = input_vec @ weight_matrix_1
out_1

array([[0.5, 0.8, 0.5],
       [0.8, 0.8, 0.3]])

In [25]:
out_2 = input_vec @ weight_matrix_2
out_2

array([[1.3, 0.9],
       [1. , 1.6]])

In [31]:
#softmax?

In [32]:
softmax(out_2[0])

array([0.59868766, 0.40131234])