<a href="https://colab.research.google.com/github/mikemwai/artificial_intelligence/blob/main/artificial_intelligence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from numpy import array
from scipy.special import softmax
from numpy.ma.core import argmax

In [3]:
input_vector = array([[1.,0.,0.,1.,0.],
                      [0.,1.,0.,1.,0.]])
weight_mat_one = array([[.2,.4,.3],
                        [.1,.5,.7],
                        [.2,.6,.8],
                        [.8,.9,.4],
                        [.1,.7,.3]])
weight_mat_two = array([[.2,.1],
                        [.5,.4],
                        [.1,.8]])

In [6]:
out_1 = input_vector @ weight_mat_one
out_1

array([[1. , 1.3, 0.7],
       [0.9, 1.4, 1.1]])

In [5]:
out_2 = out_1@weight_mat_two
out_2

array([[0.92, 1.18],
       [0.99, 1.53]])

In [7]:
out_2[0]

array([0.92, 1.18])

In [ ]:
#softmax?

In [12]:
softmax(out_1[0])

array([0.3235537 , 0.43675182, 0.23969448])

In [11]:
softmax(out_2[0])

array([0.43536371, 0.56463629])

In [10]:
softmax(out_2[1])

array([0.36818758, 0.63181242])

In [ ]:
#argmax?